/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.h                                                */
/*  DATE        :Tue, Mar 22, 2011                                     */
/*  DESCRIPTION :Header file of sbrk file                              */
/*  CPU TYPE    :SH7045F                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
/* size of area managed by sbrk */
#define HEAPSIZE 0x600
