/***********************************************************************/
/*                                                                     */
/*  FILE        :SHPrototype.cpp                                       */
/*  DATE        :Mon, Mar 21, 2011                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :SH7045F                                               */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
                  
#include "../../../stf/datatype/Time.h"
//#include "../../../stf/datatype/DCM.h"

//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	stf::datatype::Time t;

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
